version: 2
jobs:
  prepare:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Show current directory
          command: pwd
      - restore_cache:
          name: Restore node modules cache
          keys:
            - node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies if no cached node_modules
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          name: Save node modules cache
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  test:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.16.3-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules cache
          key: node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Unit test
          command: npm test -- --configuration=ci
      # TODO soon
      #      - run:
      #        name: E2E
      #        command: npm run e2e
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules cache
          key: node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Building
          command: npm run build
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - www
            - package.json
            - firebase.json
            - .firebaserc
  deploy:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/workspace
    steps:
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: change user npm privilege
          command: npm set prefix=/home/circleci/npm && echo 'export PATH=$HOME/circleci/npm/bin:$PATH' >> /home/circleci/.bashrc
      - run:
          name: Install Firebase
          command: npm install -g firebase-tools@7.3.1
      - run:
          name: Deploy Master to Firebase
          command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
      - run:
          name: URL to firebase deploy dashboard
          command: echo https://console.firebase.google.com/u/0/project/scoring-between-two-castles/hosting/main
workflows:
  version: 2
  pull-request:
    jobs:
      - prepare:
          filters:
            branches:
              only:
                - /bug(|fix)\/.*/
                - /feat(|ure)\/.*/
      - test:
          filters:
            branches:
              only:
                - /bug(|fix)\/.*/
                - /feat(|ure)\/.*/
          requires:
            - prepare
      - build:
          filters:
            branches:
              only:
                - /bug(|fix)\/.*/
                - /feat(|ure)\/.*/
          requires:
            - prepare
  build-deploy:
    # ignore any commit on any branch by default
    # Deploy only on version tags
    jobs:
      - prepare:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){1,2}(|-\w+)$/
      - build:
          requires:
            - prepare
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){1,2}(|-\w+)$/
      - deploy:
          requires:
            - build
          filters:
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){1,2}(|-\w+)$/
