import { RoomDefinition } from '../models/rooms/room.type';
import { ImmediatePointsRule } from '@app/rules/immediate-points';
import { AnywhereRule } from '@app/rules/anywhere';
import { AllTypesRule } from '@app/rules/all-types';
import { AllVerticalRule } from '@app/rules/all-vertical';
import {
  VerticalDirections,
  AllDirections,
  HorizontalDirections,
  AllRoomTypes,
  AllRegularRoomTypes,
} from '@app/helpers/room-combinations';
import { AdjacentRule } from '@app/rules/adjacent';
import { exclude } from '@app/helpers/exclude-list';
import { ConnectedRule } from '@app/rules/connected';
import { ConsecutiveRule } from '@app/rules/consecutive';
import { Direction } from '@app/models/grid-linked-list/grid-node-traverser';
export const rooms: RoomDefinition[] = [
         {
           name: 'afternoon tea room',
           type: 'food',
           hanging: 'torch',
           rule: new AdjacentRule(2, VerticalDirections, 'type', ['sleeping']),
         },
         {
           name: 'archery range',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'corridor'),
         },
         {
           name: 'armory',
           type: 'downstairs',
           hanging: 'painting',
           rule: new AllVerticalRule(2, VerticalDirections, ['specialty']),
         },
         {
           name: 'aviary',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'utility'),
         },
         {
           name: 'bakery',
           type: 'food',
           hanging: 'crest',
           rule: new AdjacentRule(2, HorizontalDirections, 'type', ['utility']),
         },
         {
           name: 'between two rooms',
           type: 'corridor',
           hanging: 'torch',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['torch']),
         },
         {
           name: 'biegarten',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'specialty'),
         },
         {
           name: 'blanket room',
           type: 'sleeping',
           hanging: 'painting',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'brandy room',
           type: 'food',
           hanging: 'painting',
           rule: new AdjacentRule(2, VerticalDirections, 'type', ['specialty']),
         },
         {
           name: 'breakfast nook',
           type: 'food',
           hanging: 'painting',
           rule: new AdjacentRule(2, VerticalDirections, 'type', ['corridor']),
         },
         {
           name: 'brewery',
           type: 'food',
           hanging: 'mirror',
           rule: new AdjacentRule(2, VerticalDirections, 'type', ['living']),
         },
         {
           name: 'broom closet',
           type: 'utility',
           hanging: 'none',
           rule: new ConnectedRule(1, 'sleeping'),
         },
         {
           name: 'bunk room',
           type: 'sleeping',
           hanging: 'painting',
           rule: new AllTypesRule(4, 2, 6, AllRegularRoomTypes),
         },
         {
           name: 'butterfly garden',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'corridor'),
         },
         {
           name: 'buttery',
           type: 'food',
           hanging: 'torch',
           rule: new AdjacentRule(2, VerticalDirections, 'type', ['corridor']),
         },
         {
           name: 'cape room',
           type: 'living',
           hanging: 'painting',
           rule: new AdjacentRule(
             2,
             ['below', 'lower-left', 'lower-right'],
             'type',
             ['downstairs']
           ),
         },
         {
           name: 'chicken coop',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'utility'),
         },
         {
           name: `children's room`,
           type: 'sleeping',
           hanging: 'crest',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'china room',
           type: 'food',
           hanging: 'mirror',
           rule: new AdjacentRule(2, HorizontalDirections, 'type', [
             'specialty',
           ]),
         },
         {
           name: 'chocolate room',
           type: 'food',
           hanging: 'painting',
           rule: new ConsecutiveRule(2, 'below', 2, 'type', 'downstairs'),
         },
         {
           name: 'coat room',
           type: 'utility',
           hanging: 'mirror',
           rule: new ConnectedRule(1, 'outdoor'),
         },
         {
           name: 'crepery',
           type: 'food',
           hanging: 'crest',
           rule: new AdjacentRule(2, VerticalDirections, 'type', ['sleeping']),
         },
         {
           name: 'crown storage',
           type: 'utility',
           hanging: 'painting',
           rule: new ConnectedRule(1, 'specialty'),
         },
         {
           name: 'crypt',
           type: 'downstairs',
           hanging: 'painting',
           rule: new AllVerticalRule(1, VerticalDirections, ['downstairs']),
         },
         {
           name: 'cutlery room',
           type: 'food',
           hanging: 'painting',
           rule: new AdjacentRule(2, VerticalDirections, 'type', ['outdoor']),
         },
         {
           name: 'dead end',
           type: 'corridor',
           hanging: 'crest',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['crest']),
         },
         {
           name: 'dining room',
           type: 'food',
           hanging: 'painting',
           rule: new AdjacentRule(2, VerticalDirections, 'type', ['food']),
         },
         {
           name: 'drawing room',
           type: 'living',
           hanging: 'painting',
           rule: new AdjacentRule(1, AllDirections, 'type', ['utility']),
         },
         {
           name: 'dreaming room',
           type: 'sleeping',
           hanging: 'painting',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'dressing room',
           type: 'sleeping',
           hanging: 'torch',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'dumbwaiter',
           type: 'utility',
           hanging: 'crest',
           rule: new ConnectedRule(1, 'food'),
         },
         {
           name: 'dungeon',
           type: 'downstairs',
           hanging: 'mirror',
           rule: new AllVerticalRule(1, VerticalDirections, ['corridor']),
         },
         {
           name: 'echo chamber',
           type: 'corridor',
           hanging: 'torch',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['torch']),
         },
         {
           name: 'escape room',
           type: 'corridor',
           hanging: 'painting',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['painting']),
         },
         {
           name: 'fireplace',
           type: 'living',
           hanging: 'mirror',
           rule: new AdjacentRule(1, AllDirections, 'type', ['food']),
         },
         {
           name: 'firewood storage',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'living'),
         },
         {
           name: 'fish pond',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'food'),
         },
         {
           name: 'flower garden',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'specialty'), //?
         },
         {
           name: 'fountain',
           type: 'specialty',
           hanging: 'none',
           rule: new ImmediatePointsRule(5),
         },
         {
           name: 'french gazebo',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'specialty'),
         },
         {
           name: 'fungus room',
           type: 'downstairs',
           hanging: 'mirror',
           rule: new AllVerticalRule(1, ['above'], ['food']),
         },
         {
           name: 'gallery',
           type: 'living',
           hanging: 'crest',
           rule: new AdjacentRule(1, AllDirections, 'type', ['utility']),
         },
         {
           name: 'game storage',
           type: 'utility',
           hanging: 'crest',
           rule: new ConnectedRule(1, 'living'),
         },
         {
           name: 'glassmaking room',
           type: 'utility',
           hanging: 'painting',
           rule: new ConnectedRule(1, 'utility'),
         },
         {
           name: 'grand balcony',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'sleeping'),
         },
         {
           name: 'grand foyer',
           type: 'specialty',
           hanging: 'none',
           rule: new AdjacentRule(1, AllDirections, 'type', AllRoomTypes),
         },
         {
           name: 'great hall',
           type: 'corridor',
           hanging: 'crest',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['crest']),
         },
         {
           name: 'guardhouse',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'downstairs'),
         },
         {
           name: 'guest room',
           type: 'sleeping',
           hanging: 'crest',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'gunpowder room',
           type: 'downstairs',
           hanging: 'painting',
           rule: new AllVerticalRule(1, VerticalDirections, ['corridor']),
         },
         {
           name: 'hall of creaking floors',
           type: 'corridor',
           hanging: 'painting',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['painting']),
         },
         {
           name: 'hall of doors',
           type: 'corridor',
           hanging: 'mirror',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['mirror']),
         },
         {
           name: 'hall of ever-closing walls',
           type: 'corridor',
           hanging: 'crest',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['crest']),
         },
         {
           name: 'hall of ghosts',
           type: 'corridor',
           hanging: 'mirror',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['mirror']),
         },
         {
           name: 'hall of knights',
           type: 'corridor',
           hanging: 'painting',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['painting']),
         },
         {
           name: 'hall of mirrors',
           type: 'corridor',
           hanging: 'mirror',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['mirror']),
         },
         {
           name: 'hall of paintings',
           type: 'corridor',
           hanging: 'painting',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['painting']),
         },
         {
           name: 'hall of portraits',
           type: 'corridor',
           hanging: 'painting',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['painting']),
         },
         {
           name: 'hall of puzzled floor',
           type: 'corridor',
           hanging: 'torch',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['torch']),
         },
         {
           name: 'hall of sculptures',
           type: 'corridor',
           hanging: 'mirror',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['mirror']),
         },
         {
           name: 'hall of windows',
           type: 'corridor',
           hanging: 'painting',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['painting']),
         },
         {
           name: 'harp room',
           type: 'living',
           hanging: 'mirror',
           rule: new AdjacentRule(1, AllDirections, 'type', ['utility']),
         },
         {
           name: 'hat room',
           type: 'living',
           hanging: 'painting',
           rule: new AdjacentRule(1, AllDirections, 'type', ['corridor']),
         },
         {
           name: 'hibernation chamber',
           type: 'sleeping',
           hanging: 'painting',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'hidden lair',
           type: 'downstairs',
           hanging: 'torch',
           rule: new AllVerticalRule(1, ['above'], ['utility']),
         },
         {
           name: 'hidden passage',
           type: 'corridor',
           hanging: 'torch',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['torch']),
         },
         {
           name: 'hidden entrance',
           type: 'downstairs',
           hanging: 'crest',
           rule: new AllVerticalRule(1, VerticalDirections, ['corridor']),
         },
         {
           name: 'ice house',
           type: 'food',
           hanging: 'torch',
           rule: new AdjacentRule(2, HorizontalDirections, 'type', ['living']),
         },
         {
           name: 'in-law suite',
           type: 'sleeping',
           hanging: 'crest',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'jewel room',
           type: 'downstairs',
           hanging: 'crest',
           rule: new AllVerticalRule(1, ['above'], ['living']),
         },
         {
           name: 'kennel',
           type: 'utility',
           hanging: 'painting',
           rule: new ConnectedRule(1, 'sleeping'),
         },
         {
           name: 'key room ',
           type: 'utility',
           hanging: 'mirror',
           rule: new ConnectedRule(1, 'corridor'),
         },
         {
           name: `king's chamber`,
           type: 'sleeping',
           hanging: 'torch',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'kitchen',
           type: 'food',
           hanging: 'torch',
           rule: new AdjacentRule(2, VerticalDirections, 'type', ['food']),
         },
         {
           name: 'kittery',
           type: 'utility',
           hanging: 'painting',
           rule: new ConnectedRule(1, 'corridor'),
         },
         {
           name: 'knight room',
           type: 'downstairs',
           hanging: 'mirror',
           rule: new AllVerticalRule(2, VerticalDirections, ['specialty']),
         },
         {
           name: 'laboratory',
           type: 'downstairs',
           hanging: 'crest',
           rule: new AllVerticalRule(1, ['above'], ['utility']),
         },
         {
           name: 'laundry room',
           type: 'utility',
           hanging: 'torch',
           rule: new ConnectedRule(1, 'food'),
         },
         {
           name: 'library',
           type: 'living',
           hanging: 'crest',
           rule: new AdjacentRule(1, AllDirections, 'type', ['specialty']),
         },
         {
           name: 'lockdown room',
           type: 'corridor',
           hanging: 'crest',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['crest']),
         },
         {
           name: 'map room',
           type: 'living',
           hanging: 'mirror',
           rule: new AdjacentRule(1, AllDirections, 'type', ['sleeping']),
         },
         {
           name: 'meat locker',
           type: 'food',
           hanging: 'crest',
           rule: new AdjacentRule(2, HorizontalDirections, 'type', ['outdoor']),
         },
         {
           name: 'meditation room',
           type: 'living',
           hanging: 'crest',
           rule: new AdjacentRule(
             2,
             exclude(AllDirections, ['below'] as Direction[]),
             'type',
             ['outdoor']
           ),
         },
         {
           name: 'midnight room',
           type: 'sleeping',
           hanging: 'crest',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'mold room',
           type: 'downstairs',
           hanging: 'crest',
           rule: new AllVerticalRule(1, ['above'], ['food']),
         },
         {
           name: 'morning tea room',
           type: 'food',
           hanging: 'crest',
           rule: new AdjacentRule(2, VerticalDirections, 'type', ['living']),
         },
         {
           name: 'mud room',
           type: 'utility',
           hanging: 'painting',
           rule: new ConnectedRule(1, 'outdoor'),
         },
         {
           name: 'nap room',
           type: 'sleeping',
           hanging: 'torch',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'nursery',
           type: 'sleeping',
           hanging: 'torch',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'observatory',
           type: 'living',
           hanging: 'torch',
           rule: new AdjacentRule(1, AllDirections, 'type', ['living']),
         },
         {
           name: 'pacing hall',
           type: 'corridor',
           hanging: 'mirror',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['mirror']),
         },
         {
           name: 'padded room',
           type: 'downstairs',
           hanging: 'torch',
           rule: new AllVerticalRule(1, ['above'], ['living']),
         },
         {
           name: 'panic room',
           type: 'utility',
           hanging: 'crest',
           rule: new ConnectedRule(1, 'specialty'),
         },
         {
           name: 'pantry',
           type: 'food',
           hanging: 'crest',
           rule: new AdjacentRule(2, HorizontalDirections, 'type', [
             'corridor',
           ]),
         },
         {
           name: 'parlor',
           type: 'living',
           hanging: 'torch',
           rule: new AdjacentRule(1, AllDirections, 'type', ['food']),
         },
         {
           name: 'pillow room',
           type: 'sleeping',
           hanging: 'torch',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'pit of despair',
           type: 'downstairs',
           hanging: 'mirror',
           rule: new AllVerticalRule(1, VerticalDirections, ['downstairs']),
         },
         {
           name: 'powder room',
           type: 'utility',
           hanging: 'mirror',
           rule: new ConnectedRule(1, 'food'),
         },
         {
           name: `prince's chambers`,
           type: 'sleeping',
           hanging: 'mirror',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'princess chambers',
           type: 'sleeping',
           hanging: 'mirror',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'promenade',
           type: 'corridor',
           hanging: 'crest',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['crest']),
         },
         {
           name: 'pumpkin garden',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'food'),
         },
         {
           name: 'puppy room',
           type: 'sleeping',
           hanging: 'painting',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'purgatory',
           type: 'corridor',
           hanging: 'torch',
           rule: new AdjacentRule(1, AllDirections, 'hanging', ['torch']),
         },
         {
           name: "queen's chambers",
           type: 'sleeping',
           hanging: 'painting',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'quiet room',
           type: 'downstairs',
           hanging: 'torch',
           rule: new AllVerticalRule(1, ['above'], ['sleeping']),
         },
         {
           name: 'rabbit room',
           type: 'sleeping',
           hanging: 'crest',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'reading room',
           type: 'living',
           hanging: 'torch',
           rule: new AdjacentRule(
             2,
             exclude(AllDirections, ['below'] as Direction[]),
             'type',
             ['outdoor']
           ),
         },
         {
           name: 'reception room',
           type: 'living',
           hanging: 'torch',
           rule: new AdjacentRule(1, AllDirections, 'type', ['corridor']),
         },
         {
           name: 'repair shop',
           type: 'utility',
           hanging: 'crest',
           rule: new ConnectedRule(1, 'utility'),
         },
         {
           name: 'rug room',
           type: 'living',
           hanging: 'painting',
           rule: new AdjacentRule(1, AllDirections, 'type', ['living']),
         },
         {
           name: 'salon',
           type: 'living',
           hanging: 'painting',
           rule: new AdjacentRule(1, AllDirections, 'type', ['sleeping']),
         },
         {
           name: 'sauerkraut room',
           type: 'food',
           hanging: 'mirror',
           rule: new AdjacentRule(2, HorizontalDirections, 'type', ['food']),
         },
         {
           name: 'sauna',
           type: 'utility',
           hanging: 'crest',
           rule: new ConnectedRule(1, 'sleeping'),
         },
         {
           name: 'schoolhouse',
           type: 'utility',
           hanging: 'torch',
           rule: new ConnectedRule(1, 'corridor'),
         },
         {
           name: 'scullery',
           type: 'food',
           hanging: 'torch',
           rule: new AdjacentRule(2, VerticalDirections, 'type', ['utility']),
         },
         {
           name: 'scythe room',
           type: 'utility',
           hanging: 'painting',
           rule: new ConnectedRule(1, 'downstairs'),
         },
         {
           name: "servant's quaters",
           type: 'sleeping',
           hanging: 'painting',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'shield room',
           type: 'utility',
           hanging: 'torch',
           rule: new ConnectedRule(1, 'downstairs'),
         },
         {
           name: 'siege food storage',
           type: 'food',
           hanging: 'crest',
           rule: new AdjacentRule(2, VerticalDirections, 'type', ['specialty']),
         },
         {
           name: 'sitting room',
           type: 'living',
           hanging: 'mirror',
           rule: new AdjacentRule(
             2,
             exclude(AllDirections, ['below']),
             'type',
             ['outdoor']
           ),
         },
         {
           name: 'snake pit',
           type: 'downstairs',
           hanging: 'mirror',
           rule: new AllVerticalRule(1, ['above'], ['living']),
         },
         {
           name: 'solar',
           type: 'sleeping',
           hanging: 'mirror',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'spice room',
           type: 'food',
           hanging: 'mirror',
           rule: new ConsecutiveRule(2, 'below', 2, 'type', 'downstairs'),
         },
         {
           name: 'spy room',
           type: 'downstairs',
           hanging: 'torch',
           rule: new AllVerticalRule(1, VerticalDirections, ['downstairs']),
         },
         {
           name: 'stables',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'downstairs'),
         },
         {
           name: 'study',
           type: 'living',
           hanging: 'mirror',
           rule: new AdjacentRule(1, AllDirections, 'type', ['specialty']),
         },
         {
           name: 'sty',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'downstairs'),
         },
         {
           name: 'subterranean tunnel',
           type: 'downstairs',
           hanging: 'painting',
           rule: new AllVerticalRule(1, ['above'], ['utility']),
         },
         {
           name: 'swimming hole',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'living'),
         },
         {
           name: 'tapestry room',
           type: 'living',
           hanging: 'crest',
           rule: new AdjacentRule(1, AllDirections, 'type', ['sleeping']),
         },
         {
           name: 'tasso room',
           type: 'sleeping',
           hanging: 'mirror',
           rule: new AllTypesRule(4, 1, 6, AllRegularRoomTypes),
         },
         {
           name: 'taxidermy showroom',
           type: 'living',
           hanging: 'torch',
           rule: new AdjacentRule(
             2,
             ['below', 'lower-left', 'lower-right'],
             'type',
             ['downstairs']
           ),
         },
         {
           name: 'terrace',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'sleeping'),
         },
         {
           name: 'the hole',
           type: 'downstairs',
           hanging: 'painting',
           rule: new AllVerticalRule(1, ['above'], ['sleeping']),
         },
         {
           name: 'tool room',
           type: 'utility',
           hanging: 'mirror',
           rule: new ConnectedRule(1, 'utility'),
         },
         {
           name: 'torch storage',
           type: 'utility',
           hanging: 'torch',
           rule: new ConnectedRule(1, 'living'),
         },
         {
           name: 'tower',
           type: 'specialty',
           hanging: 'none',
           rule: new AllVerticalRule(1, ['below'], AllRoomTypes),
         },
         {
           name: 'treasure room',
           type: 'downstairs',
           hanging: 'crest',
           rule: new AllVerticalRule(1, ['above'], ['sleeping']),
         },
         {
           name: 'turtle pond',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'sleeping'),
         },
         {
           name: 'vegetable garden',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'food'),
         },
         {
           name: 'venus grotto',
           type: 'downstairs',
           hanging: 'torch',
           rule: new AllVerticalRule(2, VerticalDirections, ['sleeping']),
         },
         {
           name: 'vestibule',
           type: 'living',
           hanging: 'crest',
           rule: new AdjacentRule(1, AllDirections, 'type', ['food']),
         },
         {
           name: 'vineyard',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'living'),
         },
         {
           name: 'waiting room',
           type: 'living',
           hanging: 'mirror',
           rule: new AdjacentRule(1, AllDirections, 'type', ['corridor']),
         },
         {
           name: 'walking path',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'corridor'),
         },
         {
           name: 'washroom',
           type: 'utility',
           hanging: 'mirror',
           rule: new ConnectedRule(1, 'living'),
         },
         {
           name: 'wine cellar',
           type: 'downstairs',
           hanging: 'torch',
           rule: new AllVerticalRule(1, ['above'], ['food']),
         },
         {
           name: 'wine room',
           type: 'food',
           hanging: 'mirror',
           rule: new AdjacentRule(2, VerticalDirections, 'type', ['sleeping']),
         },
         {
           name: 'winter garden',
           type: 'outdoor',
           hanging: 'none',
           rule: new AnywhereRule(1, 'utility'),
         },
       ];
